---
title: "Useful Python packages"
author: "John Fee"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

# Creating documents

- [nbconvert](https://nbconvert.readthedocs.io/en/latest/)
  - Convert Jupyter notebooks to other formats (e.g. html)

# Data processing

- [polars](https://pola.rs/)
  - A Rust-based DataFrame package that is faster than pandas and has a much nicer API
- [pyjanitor](https://pyjanitor-devs.github.io/pyjanitor/)
  - I have only used the `clean_names` functionality (similar to R's janitor package)
  
# Plotting

- [plotnine](https://plotnine.org/)
  - ggplot2 port to Python
- [altair](https://altair-viz.github.io/index.html)
  - Promising visualization package
# Coding/Productivity

# Dev tools

- [pytest](https://docs.pytest.org/en/stable/)
  - Widely used testing package
- [ruff](https://docs.astral.sh/ruff/)
  - Code formatter and checker
- [jupytext](https://jupytext.readthedocs.io/en/latest/)
  - Useful to convert Jupyter notebooks into something that can be version controlled
- [marimo](https://marimo.io/)
  - Interesting alternative to Jupyter notebooks - git friendly!
- [rich](https://rich.readthedocs.io/en/stable/introduction.html)
  - Package for displaying *rich* text in the terminal.  Also helpful for debugging!
- [cyclopts](https://github.com/BrianPugh/cyclopts)
  - Promising CLI package
- [pdoc](https://pdoc.dev/docs/pdoc.html) and [MkDocs](https://www.mkdocs.org/) are package documentation generators worth trying out

Also some generally helpful links for Python packaging:

- [Python packaging user guide](https://packaging.python.org/en/latest/overview/)

